version: '3.5'

services:
  mongodb:
    image: mongo
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: